### ISSUE TITLE
Does WPA kill pods if the queue length decreases?

### ISSUE THREAD

**Issue by robin-ency** [practo/k8s-worker-pod-autoscaler#144]
We have deployed WPA on AWS EKS and are using it with some success. We have typically tried running with a maximum of 10 pods (replicas) and all went well. Now we have increased this to 50 and we are noticing pods are randomly quitting with no discernible reason. Its like there is a service that is shutting down a pod midway.

Does WPA kill pods midway as the queue length decreases? We have long running tasks that need around 1-2 hours to process, so we need the pods to finish completely and then quit. WPA should only be responsible for scaling up, and for scaling down, it should not kill existing running pods. Is this what you mean by "disruption"? does "disruption" mean you will:

A. Kill running pods
B. Not create additional pods and leave the running pods on

We are running a python app on EKS, this is the YAML for the app:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-consumer
spec:
  selector:
    matchLabels:
      app: sqs-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: sqs-consumer
    spec:
      hostNetwork: true
      containers:
      - name: sqs-consumer
        image: XXXXXXXXXXXXXXXXXXXXXXX.dkr.ecr.XXXXX.amazonaws.com/
        env:
          - name: ENVIRONMENT
            value: "production"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CONTAINER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
        resources:
          limits:
            memory: "2Gi"
          requests:
            memory: "2Gi"
```

This is the current WPA config:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerpodautoscaler
  namespace: woker-pod-autoscaler
  labels:
    app: workerpodautoscaler
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workerpodautoscaler
  template:
    metadata:
      labels:
        app: workerpodautoscaler
    spec:
      serviceAccountName: workerpodautoscaler
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: wpa
          env:
          image: practodev/workerpodautoscaler:{{ WPA_TAG }}
          imagePullPolicy: Always
          command:
            - /workerpodautoscaler
            - run
            - --resync-period=20
            - --wpa-threads=10
            - --aws-regions={{ WPA_AWS_REGIONS }}
            - --sqs-short-poll-interval=20
            - --sqs-long-poll-interval=20
            - --k8s-api-qps=5.0
            - --k8s-api-burst=10
            - --wpa-default-max-disruption=100%
            - --queue-services=sqs,beanstalkd
            - -v=2
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
```
And the other WPA config:
```
apiVersion: k8s.practo.dev/v1
kind: WorkerPodAutoScaler
metadata:
  name: wpa
spec:
  minReplicas: 0
  maxReplicas: 0
  deploymentName: sqs-consumer
  queueURI: https://sqs.XXXXXXXXXXXXXXXXXXXXXXX.amazonaws.com/XXXXXXXXXXXXXXXXXXXXXXX/
  targetMessagesPerWorker: 2
  secondsToProcessOneJob: 7200
  maxDisruption: "0%"
```

Any help would be greatly appreciated to help us resolve this issue of pods randomly shutting down midway processing.
