### ISSUE TITLE
minReplicas can be greater than maxReplicas

### ISSUE THREAD

**Issue by ishanjoshi02** [practo/k8s-worker-pod-autoscaler#92]
Used `k edit wpa -n <context>` to open the WPA spec in vim. 

Was able to set minReplicas to 10, and maxReplicas to 1 for the same pod.

**Comment by alok87** [comment]
Validation needs to be made better for the CRD

**Comment by adityabhatia02** [comment]
Unable to edit min-replicas in kubernetes v1.18.0; Failing with error:
`Invalid value: "": "spec" must validate one and only one schema (oneOf). Found 2 valid alternatives`

**Comment by alok87** [comment]
Issue is happening because the WPA has got created and the object has both `replicasSetName` and `deploymentName`. 
```yaml
spec:
    maxDisruption: null
    maxReplicas: 1
    minReplicas: 0
    queueURI: URI-sample
    replicaSetName: ""
    deploymentName: mailsender
    secondsToProcessOneJob: 0
    targetMessagesPerWorker: 1
```

cc @matkam
